<?php

require_once dirname(__FILE__) . '/../../../app/models/MoneyModel.php';

/**
 * Test class for MoneyModel.
 * Generated by PHPUnit on 2012-09-23 at 17:18:53.
 */
class MoneyModelTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MoneyModel
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MoneyModel;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers MoneyModel::getM
	 * @todo Implement testGetM().
	 */
	public function testGetM() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers MoneyModel::negate
	 * @todo Implement testNegate().
	 */
	public function testNegate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
